# Generated by Django 5.2.5 on 2025-08-31 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('telefone', models.CharField(max_length=11, verbose_name='Telefone')),
                ('idade', models.IntegerField(null=True, verbose_name='Idade')),
            ],
        ),
    ]
