# Generated by Django 5.2.5 on 2025-09-01 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filmes',
            options={'ordering': ['filme'], 'verbose_name': 'Filme', 'verbose_name_plural': 'Filmes'},
        ),
        migrations.AlterModelOptions(
            name='generos',
            options={'ordering': ['genero'], 'verbose_name': 'Genero', 'verbose_name_plural': 'Generos'},
        ),
    ]
